apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: flake-cloud-controller
  name: flake-cloud-controller
  namespace: default
spec:
  selector:
    matchLabels:
      k8s-app: flake-cloud-controller
  template:
    metadata:
      labels:
        k8s-app: flake-cloud-controller
    spec:
      hostNetwork: true
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: flake-cloud-controller
        image: flake/cloud-controller:v1.0.0
        imagePullPolicy: IfNotPresent
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      restartPolicy: Always
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: flake-cloud-controller
  namespace: default
rules:
- apiGroups: ["devices.kubeedge.io"]
  resources: ["devices","pods","devicemodel"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: flake-cloud-controller-rbac
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
roleRef:
  kind: Role
  name: flake-cloud-controller
  apiGroup: rbac.authorization.k8s.io
